export declare const ERROR_CODES: {
    readonly AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED";
    readonly AUTHENTICATED_USER_NOT_LINKED: "AUTHENTICATED_USER_NOT_LINKED";
    readonly USER_DISABLED: "USER_DISABLED";
    readonly FORBIDDEN: "FORBIDDEN";
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly NOT_FOUND: "NOT_FOUND";
    readonly CONFLICT: "CONFLICT";
    readonly ILLEGAL_STATE_TRANSITION: "ILLEGAL_STATE_TRANSITION";
    readonly IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT";
    readonly PROVIDER_ERROR: "PROVIDER_ERROR";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
};
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
